#define ENGLISH_ALPHABET_COUNT 26
#define MAX_RANDOM_NUMBER 20
#define MAX_RANDOM_DOUBLE_NUM 5

#define MAX_NUMBERS_BEFORE_DOT 2
#define DOT '.'
#define MAX_TEN 10

#define FILE_INVOICES_NAME "files/INVOICES"
#define FILE_PAYMENTS_NAME "files/PAYMENTS"

#define ASCII_A_CHAR 97
#define TERMINATION_ZERO '\0'